import AboutPage from "@/app/components/AboutPage/AboutPage";
import Head from "next/head";

const About = () => {
  return (
    <div className="">
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AboutPage />
    </div>
  );
};

export default About;
