import Head from "next/head";

const Home = () => {
  return (
    <div className="">
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="">Portfolio</h1>
      </main>
    </div>
  );
};

export default Home;
