export const Projects = [
  {
    type: "webDev",
    title: "Everyworld",
    year: "2024",
    link: "",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb: "Combat-focused, third-person action game.",
    coverImage: "everyworld",
    tags: ["React", "Next.js", "TailwindCSS"],
  },
  {
    type: "webDev",
    title: "Food Share",
    year: "2023",
    link: "",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb: "Combat-focused, third-person action game.",
    coverImage: "foodshare",
    tags: ["HTML", "MongoDB"],
  },
  {
    type: "game",
    title: "Ember Point",
    link: "",
    year: "2023",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb:
      "Ember Point is a combat-focused, third-person action game. Play as a disgraced defector from a militaristic mega-corporation, Gravitus, who is stuck cleaning up the terrible mess his former employers left behind — all while wielding a top-secret “cure” for a gruesome disease.",
    coverImage: "emberpoint",
    tags: ["UE5"],
  },
  {
    coverImage: "escapethecatacombs",
    year: "2023",
    type: "game",
    title: "Escape the Catacombs",
    link: "",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb:
      "A 2D top-down heist game where you control a thieving cat. Navigate corridors, evade guards, and avoid traps as you embark on your daring heist. Use your agility and cunning to outsmart the Witches and secure your freedom in this strategic adventure.",
    tags: ["Unity 2D", "C#"],
  },
  {
    coverImage: "shadowfrog",
    year: "2023",
    type: "game",
    title: "Shadow Frog",
    link: "",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb:
      "Assume the role of a mysterious frog who awakens in an unknown location with no recollection of their identity or past. To survive, players must confront their forgotten memories, solve intricate puzzles, and interact with mysterious characters to unravel the sinister truth lurking beneath the surface.",
    tags: ["Unity 2D", "C#", "Adobe PhotoShop"],
  },
  {
    type: "game",
    title: "King of the Colony",
    link: "",
    year: "2023",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb:
      "Assuming the role of a human disguised as a rat, you embark on a mission to undermine the activities of a rat colony thriving beneath your city. Through a blend of time management and inventive puzzle-solving, players navigate a small subterranean world while uncovering the unforeseen repercussions of emerging urban policies.",
    coverImage: "kingofthecolony",
    tags: ["Unity 2D", "C#"],
  },

  {
    coverImage: "hackrunner",
    type: "moCap",
    year: "2023",
    title: "Hack Runner",
    link: "",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb:
      "A fast paced motion capture film centered around a skilled hacker's mission to steal highly classified data. The film seamlessly shifts between two parallel worlds: a cutting-edge virtual reality realm where the hacker executes daring heists, and the gritty real world where he becomes a fugitive, desperately evading three relentless pursuers.",
    tags: ["UE5", "Motive", "MotionBuilder", "OptiTrack"],
  },
  {
    type: "moCap",
    year: "2023",
    title: "An Epic Death",
    link: "",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb:
      "Two individuals engage in a visceral battle to the death.  As the conflict unfolds within a stunningly detailed environment, the film encapsulates the raw power, tension, and ultimate fate of these combatants in a brief yet gripping cinematic experience.",
    coverImage: "anepicdeath",
    tags: ["UE5", "Motive", "MotionBuilder", "OptiTrack"],
  },
];
