import {
  BugIcon,
  CryptoCoin,
  FireIcon,
  ForkKnifeIcon,
  HTMLIcon,
  MicroChipIcon,
  SkeletonIcon,
  SkullAndBonesIcon,
  TeethIcon,
} from "../../icons";

export const Projects = [
  {
    type: "webDev",
    title: "Everyworld",
    icon: <CryptoCoin />,
    year: "2024",
    link: "https://everyworld.com/",
    engine: "Unreal Engine 5 (2023)",
    role: "Frontend Developer",
    blurb:
      "A dynamic platform showcasing immersive digital experiences and Web3 innovations. EveryWorld integrates cutting-edge technologies to create engaging virtual environments and interactive applications, highlighting a commitment to exploring the future of digital worlds.",
    coverImage: "everyworld",
    tags: ["React", "TypeScript", "Next.js", "TailwindCSS", "Zustand"],
  },

  {
    type: "game",
    title: "Ember Point",
    teamSize: "11",
    icon: <FireIcon />,
    link: "https://store.steampowered.com/app/2912870/Ember_Point/",
    year: "2023",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb:
      "Ember Point is a combat-focused, third-person action game. Play as a disgraced defector from a militaristic mega-corporation, Gravitus, who is stuck cleaning up the terrible mess his former employers left behind — all while wielding a top-secret “cure” for a gruesome disease.",
    coverImage: "emberpoint",
    tags: ["UE5"],
  },
  {
    coverImage: "escapethecatacombs",
    year: "2023",
    type: "game",
    teamSize: "4",
    icon: <SkeletonIcon />,
    title: "Escape the Catacombs",
    link: "https://junkim20.itch.io/escape-the-catacombs",
    engine: "Unreal Engine 5 (2023)",
    role: "Technical Designer",
    blurb:
      "A 2D top-down heist game where you control a thieving cat, navigating a witch’s lair to steal valuable items. Use agility and strategy to evade guards and traps as you plan your daring escape.",
    tags: ["Unity 2D", "C#"],
  },
  {
    coverImage: "shadowfrog",
    year: "2023",
    type: "game",
    icon: <TeethIcon />,
    teamSize: "2",
    title: "Shadow Frog",
    link: "https://billiton.itch.io/shadow-frog",
    engine: "Unreal Engine 5 (2023)",
    role: "Narrative and Game Artist",
    blurb:
      " A visual-novel horror game where you play as a mysterious frog with no memory, navigating an eerie village that feels hauntingly familiar. Uncover dark secrets, solve puzzles, and confront forgotten memories to survive the sinister atmosphere surrounding shadowy frogs and unravel the chilling truth.",
    tags: ["Unity 2D", "C#", "Adobe PhotoShop"],
  },

  {
    type: "game",
    title: "King of the Colony",
    teamSize: "3",
    icon: <SkullAndBonesIcon />,
    link: "https://juju136.itch.io/king-of-the-colony",
    year: "2023",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer & Technical Designer",
    blurb:
      "Assuming the role of a human disguised as a rat, you embark on a mission to undermine the activities of a rat colony thriving beneath your city. Through a blend of time management and inventive puzzle-solving, players navigate a small subterranean world while uncovering the unforeseen repercussions of emerging urban policies.",
    coverImage: "kingofthecolony",
    tags: ["Unity 2D", "C#"],
  },

  {
    coverImage: "hackrunner",
    type: "moCap",
    teamSize: "2",
    year: "2023",
    title: "Hack Runner",
    icon: <MicroChipIcon />,
    link: "https://www.youtube.com/watch?v=1jlmHrUacPI",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer",
    blurb:
      "A fast-paced motion capture film about a hacker who navigates a virtual reality world to steal classified data while evading pursuers in the real world. The film blends high-tech heists with intense chase sequences, leaving audiences wondering if the hacker can outsmart his enemies and survive.",
    tags: ["UE5", "Motive", "MotionBuilder", "OptiTrack"],
  },
  {
    type: "moCap",
    year: "2023",
    title: "An Epic Death",
    icon: <BugIcon />,
    teamSize: "2",
    link: "https://www.youtube.com/watch?v=O0I09iZXVgM",
    engine: "Unreal Engine 5 (2023)",
    role: "Motion Capture Developer",
    blurb:
      "Two individuals engage in a visceral battle to the death.  As the conflict unfolds within a stunningly detailed environment, the film encapsulates the raw power, tension, and ultimate fate of these combatants in a brief yet gripping cinematic experience.",
    coverImage: "anepicdeath",
    tags: ["UE5", "Motive", "MotionBuilder", "OptiTrack"],
  },
  {
    type: "webDev",
    title: "Food Share",
    icon: <ForkKnifeIcon />,
    year: "2023",
    teamSize: "4",
    link: "https://github.com/harryrios/FoodShare",
    engine: "Unreal Engine 5 (2023)",
    role: "Lead Frontend Developer",
    blurb:
      "A dashboard-style system for managing food pantry operations, including inventory, donations, and distributions. It streamlines tasks and enhances efficiency.",
    coverImage: "foodshare",
    tags: ["HTML", "PostgreSQL", "sqlAlchemy"],
  },
  {
    type: "webDev",
    title: "Sodoku Solver",
    teamSize: "1",
    year: "2023",
    icon: <HTMLIcon />,
    link: "https://github.com/jsoranno15/Sudoku-Solver",
    engine: "",
    role: "Programmer",
    blurb:
      "A Sudoku puzzle solver designed using the backtracking algorithm to efficiently solve even the most difficult puzzles. This project highlights algorithmic problem-solving skills by exploring all potential configurations to find valid solutions.",
    coverImage: "sudokusolver",
    tags: ["Python", "CLI"],
  },
];
