export const Experience = [
  {
    timeFrame: "Oct 2024 — Present",
    title: "Game Engineer — Hometopia",
    points: [
      "Designed and implemented UI/UX elements and menu systems in Unity for Hometopia, including an in-game screenshot tool that allows players to capture and share their creations to their portfolio and Steam profile.",
      "Integrated features such as post-processing settings, field-of-view settings, pop-ups, menus, buttons, toggles, search fields, animations, download systems, and save-to-portfolio systems to optimize interface performance and polish user workflows, contributing to Hometopia's successful Early Access front-page feature on Steam.",
    ],
    skills: ["Unity", "C#", "Figma"],
    link: "https://www.hometopia.com/",
    image: "hometopia.webp",
  },
  {
    timeFrame: "Jan 2024 — July 2024",
    title: "Frontend Engineer — Everyrealm",
    points: [
      "Architected and maintained the front end of Everyworld, a high-performance Web3 application serving 30,000 active users, using React, Next.js, TypeScript, Zustand, and Tailwind CSS.",
      "Executed comprehensive testing, debugging, and deployment of a dynamic codebase with numerous evolving features, ensuring seamless adaptation and continuous improvement using GitHub for version control and Vercel for deployment.",
      "Translated complex Figma designs into responsive, reusable React components, integrating features like account settings, crypto wallet connection, home pages, landing pages, profile pages, pop ups, and player tier/badge systems.",
      "Collaborated with backend developers to integrate AWS Lambda, DynamoDB, and API Gateway, significantly boosting application performance and scalability.",
    ],
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "Zustand",
      "AWS Lambda",
      "DynamoDB",
    ],
    link: "https://www.everyworld.com/",
    image: "everyrealm.jpg",
  },
  {
    timeFrame: "Aug 2022 — April 2023",
    title: "Coding Teacher — Penguin Coding School",
    points: [
      "Instructed classes of 2-25 students at 4 different expertise levels in Python, Lua, JavaScript, and Scratch ",
      "Created custom lesson plans at varying experience levels based on student interests",
    ],
    skills: [
      "Python",
      "Lua",
      "JavaScript",
      "Scratch",
      "Management ",
      "Leadership",
      "Instructing",
    ],
    link: "https://penguincodingschool.com/",
    image: "pcs.jpg",
  },
  {
    timeFrame: "Sept 2019 — April 2023",
    title: "New York University — Tandon School of Engineering",
    points: [
      "Bachelor's of Science in Computer Science, Minor in Game Engineering",
      "Dean's List 2023",
    ],
    skills: [
      "Design & Analysis of Algorithms",
      "Game Development",
      "3D Animation",
      "Artifical Intelligence",
      "Motion Capture",
      "Operating Systems",
      "Software Engineering",
    ],
    image: "nyu.jpg",
  },
];
